format = """
$username\
$directory\
[](fg:#06969A bg:#33658A)\
$git_branch\
$git_status\
[ ](fg:#33658A)\
$status
"""

# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "#86BBD8"
style_root = "#9A348E"
format = '[]($style)[$user ](bg:$style)[](fg:$style bg:#06969A)'

[directory]
style = "bg:#06969A"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#33658A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#33658A"
format = '[$all_status$ahead_behind ]($style)'

