#!/bin/bash

option0="lock"
option1="logout"
option2="reboot"
option3="shutdown"

options="$option0\n$option1\n$option2\n$option3"

chosen="$(echo -e "$options" | rofi -lines 4 -dmenu -p "power" -theme Arc-Dark -width 30)"
case $chosen in
	$option0)
		betterlockscreen -l;;
	$option1)
		bspc quit;;
	$option2)
		sudo reboot;;
	$option3)
		sudo poweroff;;
esac
